version: 2.1
orbs:
  node: circleci/node@3.0.0


defaults: &defaults
  working_directory: ~/project/war3-another-overlay
  docker:
    - image: node:lts-stretch-slim


jobs:
  install:
    <<: *defaults
    steps:
      - run: npm install
      - persist_to_workspace:
          root: ~/project
          paths:
            - war3-another-overlay
  lint:
    <<: *defaults
    steps:
      - run: npm run lint

workflows:
  setup:
    jobs:
      - lint
