export const NAVBAR_WIDTH = 1400;
export const NAVBAR_HEIGHT = 46;

export const RESOURCE_TEXT_COLOR = {
  gold: 'text-yellow-400',
  lumber: 'text-green-400',
  food: 'text-green-400',
  foodSmallTax: 'text-yellow-400',
  foodBigTax: 'text-red-400',
  unit: 'text-purple-400',
  worker: 'text-blue-400',
  apm: 'text-emerald-400',
  ping: 'text-gray-700',
};

export const RESOURCE_GRADIENTS = {
  gold: 'from-yellow-600',
  lumber: 'from-green-700',
  food: 'from-red-700',
  unit: 'from-purple-700',
  worker: 'from-blue-700',
  upgrades: 'from-gray-200',
};

export const PLAYER_GRADIENTS = {
  red: 'from-red-700',
  blue: 'from-blue-500',
  teal: 'from-teal-600',
  purple: 'from-purple-800',
  yellow: 'from-yellow-400',
  orange: 'from-orange-500',
  green: 'from-green-600',
  pink: 'from-pink-500',
  gray: 'from-gray-400',
  'light-blue': 'from-blue-400',
  'dark-green': 'from-green-800',
  brown: 'from-yellow-800',
  maroon: 'from-red-500',
  navy: 'from-blue-800',
  turquoise: 'from-lime-500',
  violet: 'from-purple-800',
  wheat: 'from-yellow-700',
  peach: 'from-orange-200',
  mint: 'from-green-400',
  lavender: 'from-purple-300',
  coal: 'from-gray-600',
  snow: 'from-gray-100',
  emerald: 'from-emerald-400',
  peanut: 'from-yellow-400',
};

export const PLAYER_BORDER_COLOR = {
  red: 'border-red-700',
  blue: 'border-blue-500',
  teal: 'border-teal-600',
  purple: 'border-purple-800',
  yellow: 'border-yellow-400',
  orange: 'border-orange-500',
  green: 'border-green-600',
  pink: 'border-pink-500',
  gray: 'border-gray-400',
  'light-blue': 'border-blue-400',
  'dark-green': 'border-green-800',
  brown: 'border-yellow-800',
  maroon: 'border-red-500',
  navy: 'border-blue-800',
  turquoise: 'border-lime-500',
  violet: 'border-purple-800',
  wheat: 'border-yellow-700',
  peach: 'border-orange-200',
  mint: 'border-green-400',
  lavender: 'border-purple-300',
  coal: 'border-gray-600',
  snow: 'border-gray-100',
  emerald: 'border-emerald-400',
  peanut: 'border-yellow-400',
};
